accounts:
  - name: alice
    coins: ["20000000000utoken", "200000000stake"]
  - name: bob
    coins: ["10000000000utoken", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["5000000utoken", "100000stake"]
