accounts:
  - name: alice
    coins: ["200000000000000uenci"]
  - name: bob
    coins: ["10000000000uenci"]
  - name: foundation
    coins: ["1uenci"]
    address: enci1a5jqux9wu4e8zfxxlv4fxh8t697rdc636n3pyk
validator:
  name: alice
  staked: "10000000000000uenci"
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["5000000uenci", "100000stake"]
genesis:
  app_state:
    mint:
      params:
        mint_denom: "uenci"
