// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: enci/charity/v1beta1/charity.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Charity defines the charity object
type Charity struct {
	CharityName string `protobuf:"bytes,1,opt,name=charity_name,json=charityName,proto3" json:"charity_name,omitempty"`
	AccAddress  string `protobuf:"bytes,2,opt,name=accAddress,proto3" json:"accAddress,omitempty"`
	Checksum    string `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
}

func (m *Charity) Reset()         { *m = Charity{} }
func (m *Charity) String() string { return proto.CompactTextString(m) }
func (*Charity) ProtoMessage()    {}
func (*Charity) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cd882a29514394e, []int{0}
}
func (m *Charity) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Charity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Charity.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Charity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Charity.Merge(m, src)
}
func (m *Charity) XXX_Size() int {
	return m.Size()
}
func (m *Charity) XXX_DiscardUnknown() {
	xxx_messageInfo_Charity.DiscardUnknown(m)
}

var xxx_messageInfo_Charity proto.InternalMessageInfo

func (m *Charity) GetCharityName() string {
	if m != nil {
		return m.CharityName
	}
	return ""
}

func (m *Charity) GetAccAddress() string {
	if m != nil {
		return m.AccAddress
	}
	return ""
}

func (m *Charity) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

// Params defines parameters of the charity module able to be changed by governance proposals
type Params struct {
	Charities []Charity `protobuf:"bytes,1,rep,name=charities,proto3" json:"charities"`
	// tax_rate defines the charity tax rate per taxable transaction message ; constrained by TaxRateLimits
	TaxRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=tax_rate,json=taxRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"tax_rate"`
	// Tax_caps represents max tax amount for each denom
	TaxCaps []TaxCap `protobuf:"bytes,3,rep,name=tax_caps,json=taxCaps,proto3" json:"tax_caps"`
	// burn_rate represents the percentage of balance to be burned from charity tax collector account per end of period
	// constrained by TaxRateLimits
	BurnRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=burn_rate,json=burnRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"burn_rate"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cd882a29514394e, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetCharities() []Charity {
	if m != nil {
		return m.Charities
	}
	return nil
}

func (m *Params) GetTaxCaps() []TaxCap {
	if m != nil {
		return m.TaxCaps
	}
	return nil
}

// TaxCap defines a tax cap for a denom
type TaxCap struct {
	Denom string                                 `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Cap   github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,2,opt,name=Cap,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"Cap"`
}

func (m *TaxCap) Reset()         { *m = TaxCap{} }
func (m *TaxCap) String() string { return proto.CompactTextString(m) }
func (*TaxCap) ProtoMessage()    {}
func (*TaxCap) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cd882a29514394e, []int{2}
}
func (m *TaxCap) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TaxCap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TaxCap.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TaxCap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaxCap.Merge(m, src)
}
func (m *TaxCap) XXX_Size() int {
	return m.Size()
}
func (m *TaxCap) XXX_DiscardUnknown() {
	xxx_messageInfo_TaxCap.DiscardUnknown(m)
}

var xxx_messageInfo_TaxCap proto.InternalMessageInfo

func (m *TaxCap) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// TaxRateLimits defines upper and lower limits to the tax_rate and burn_rate
type TaxRateLimits struct {
	RateMin     github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=rate_min,json=rateMin,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"rate_min"`
	TaxRateMax  github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=tax_rate_max,json=taxRateMax,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"tax_rate_max"`
	BurnRateMax github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=burn_rate_max,json=burnRateMax,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"burn_rate_max"`
}

func (m *TaxRateLimits) Reset()         { *m = TaxRateLimits{} }
func (m *TaxRateLimits) String() string { return proto.CompactTextString(m) }
func (*TaxRateLimits) ProtoMessage()    {}
func (*TaxRateLimits) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cd882a29514394e, []int{3}
}
func (m *TaxRateLimits) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TaxRateLimits) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TaxRateLimits.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TaxRateLimits) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaxRateLimits.Merge(m, src)
}
func (m *TaxRateLimits) XXX_Size() int {
	return m.Size()
}
func (m *TaxRateLimits) XXX_DiscardUnknown() {
	xxx_messageInfo_TaxRateLimits.DiscardUnknown(m)
}

var xxx_messageInfo_TaxRateLimits proto.InternalMessageInfo

// CollectionPeriod defines the record of each tax collection period
type CollectionPeriod struct {
	Period uint64 `protobuf:"varint,1,opt,name=period,proto3" json:"period,omitempty"`
	// Tax collected during entire period
	TaxCollected github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=tax_collected,json=taxCollected,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"tax_collected"`
	// Amount paid out to target charities
	Payouts []Payout `protobuf:"bytes,3,rep,name=payouts,proto3" json:"payouts"`
}

func (m *CollectionPeriod) Reset()         { *m = CollectionPeriod{} }
func (m *CollectionPeriod) String() string { return proto.CompactTextString(m) }
func (*CollectionPeriod) ProtoMessage()    {}
func (*CollectionPeriod) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cd882a29514394e, []int{4}
}
func (m *CollectionPeriod) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CollectionPeriod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CollectionPeriod.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CollectionPeriod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionPeriod.Merge(m, src)
}
func (m *CollectionPeriod) XXX_Size() int {
	return m.Size()
}
func (m *CollectionPeriod) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionPeriod.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionPeriod proto.InternalMessageInfo

func (m *CollectionPeriod) GetPeriod() uint64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *CollectionPeriod) GetTaxCollected() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.TaxCollected
	}
	return nil
}

func (m *CollectionPeriod) GetPayouts() []Payout {
	if m != nil {
		return m.Payouts
	}
	return nil
}

// Payout defines a payment to a charity
type Payout struct {
	Recipientaddr string                                   `protobuf:"bytes,1,opt,name=recipientaddr,proto3" json:"recipientaddr,omitempty"`
	Coins         github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=coins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"coins"`
}

func (m *Payout) Reset()         { *m = Payout{} }
func (m *Payout) String() string { return proto.CompactTextString(m) }
func (*Payout) ProtoMessage()    {}
func (*Payout) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cd882a29514394e, []int{5}
}
func (m *Payout) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Payout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Payout.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Payout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payout.Merge(m, src)
}
func (m *Payout) XXX_Size() int {
	return m.Size()
}
func (m *Payout) XXX_DiscardUnknown() {
	xxx_messageInfo_Payout.DiscardUnknown(m)
}

var xxx_messageInfo_Payout proto.InternalMessageInfo

func (m *Payout) GetRecipientaddr() string {
	if m != nil {
		return m.Recipientaddr
	}
	return ""
}

func (m *Payout) GetCoins() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Coins
	}
	return nil
}

// TaxProceeds defines a TaxProceed object containing sdk.Coins field
type TaxProceeds struct {
	TaxProceeds github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=tax_proceeds,json=taxProceeds,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"tax_proceeds"`
}

func (m *TaxProceeds) Reset()         { *m = TaxProceeds{} }
func (m *TaxProceeds) String() string { return proto.CompactTextString(m) }
func (*TaxProceeds) ProtoMessage()    {}
func (*TaxProceeds) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cd882a29514394e, []int{6}
}
func (m *TaxProceeds) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TaxProceeds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TaxProceeds.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TaxProceeds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaxProceeds.Merge(m, src)
}
func (m *TaxProceeds) XXX_Size() int {
	return m.Size()
}
func (m *TaxProceeds) XXX_DiscardUnknown() {
	xxx_messageInfo_TaxProceeds.DiscardUnknown(m)
}

var xxx_messageInfo_TaxProceeds proto.InternalMessageInfo

func (m *TaxProceeds) GetTaxProceeds() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.TaxProceeds
	}
	return nil
}

// Payouts defines a slice of Payout
type Payouts struct {
	Payouts []Payout `protobuf:"bytes,1,rep,name=payouts,proto3" json:"payouts"`
}

func (m *Payouts) Reset()         { *m = Payouts{} }
func (m *Payouts) String() string { return proto.CompactTextString(m) }
func (*Payouts) ProtoMessage()    {}
func (*Payouts) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cd882a29514394e, []int{7}
}
func (m *Payouts) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Payouts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Payouts.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Payouts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payouts.Merge(m, src)
}
func (m *Payouts) XXX_Size() int {
	return m.Size()
}
func (m *Payouts) XXX_DiscardUnknown() {
	xxx_messageInfo_Payouts.DiscardUnknown(m)
}

var xxx_messageInfo_Payouts proto.InternalMessageInfo

func (m *Payouts) GetPayouts() []Payout {
	if m != nil {
		return m.Payouts
	}
	return nil
}

func init() {
	proto.RegisterType((*Charity)(nil), "enci.charity.v1beta1.Charity")
	proto.RegisterType((*Params)(nil), "enci.charity.v1beta1.Params")
	proto.RegisterType((*TaxCap)(nil), "enci.charity.v1beta1.TaxCap")
	proto.RegisterType((*TaxRateLimits)(nil), "enci.charity.v1beta1.TaxRateLimits")
	proto.RegisterType((*CollectionPeriod)(nil), "enci.charity.v1beta1.CollectionPeriod")
	proto.RegisterType((*Payout)(nil), "enci.charity.v1beta1.Payout")
	proto.RegisterType((*TaxProceeds)(nil), "enci.charity.v1beta1.TaxProceeds")
	proto.RegisterType((*Payouts)(nil), "enci.charity.v1beta1.Payouts")
}

func init() {
	proto.RegisterFile("enci/charity/v1beta1/charity.proto", fileDescriptor_6cd882a29514394e)
}

var fileDescriptor_6cd882a29514394e = []byte{
	// 619 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xdf, 0x6a, 0x13, 0x4f,
	0x14, 0xce, 0x26, 0x6d, 0xd2, 0x9e, 0x34, 0xf0, 0x63, 0x28, 0x3f, 0x62, 0xd1, 0x6d, 0x5d, 0x44,
	0xea, 0x85, 0x1b, 0xab, 0xb7, 0x0a, 0x36, 0x2b, 0x48, 0xd1, 0x4a, 0x58, 0x7a, 0xe5, 0x4d, 0x3c,
	0x99, 0x1d, 0x9a, 0xa1, 0xdd, 0x99, 0x65, 0x67, 0x22, 0xdb, 0x0b, 0xc1, 0x47, 0xd0, 0x57, 0xf0,
	0xd2, 0x27, 0xe9, 0x65, 0x2f, 0xa5, 0x17, 0x55, 0xda, 0x17, 0x91, 0xf9, 0x93, 0xa6, 0x42, 0x41,
	0x1b, 0xf4, 0x6a, 0xe7, 0xcc, 0x7e, 0xe7, 0x3b, 0xdf, 0xf9, 0xe6, 0xcc, 0x40, 0xc4, 0x04, 0xe5,
	0x3d, 0x3a, 0xc6, 0x92, 0xeb, 0xa3, 0xde, 0xfb, 0xad, 0x11, 0xd3, 0xb8, 0x35, 0x8d, 0xe3, 0xa2,
	0x94, 0x5a, 0x92, 0x55, 0x83, 0x89, 0xa7, 0x7b, 0x1e, 0xb3, 0xb6, 0xba, 0x2f, 0xf7, 0xa5, 0x05,
	0xf4, 0xcc, 0xca, 0x61, 0xd7, 0x42, 0x2a, 0x55, 0x2e, 0x55, 0x6f, 0x84, 0x8a, 0xcd, 0xe8, 0x24,
	0x17, 0xee, 0x7f, 0x34, 0x86, 0x56, 0xe2, 0x88, 0xc8, 0x5d, 0x58, 0xf1, 0x9c, 0x43, 0x81, 0x39,
	0xeb, 0x06, 0x1b, 0xc1, 0xe6, 0x72, 0xda, 0xf6, 0x7b, 0x6f, 0x30, 0x67, 0x24, 0x04, 0x40, 0x4a,
	0xb7, 0xb3, 0xac, 0x64, 0x4a, 0x75, 0xeb, 0x16, 0x70, 0x65, 0x87, 0xac, 0xc1, 0x12, 0x1d, 0x33,
	0x7a, 0xa0, 0x26, 0x79, 0xb7, 0x61, 0xff, 0x5e, 0xc6, 0xd1, 0x97, 0x3a, 0x34, 0x07, 0x58, 0x62,
	0xae, 0xc8, 0x36, 0x2c, 0x3b, 0x56, 0xce, 0x54, 0x37, 0xd8, 0x68, 0x6c, 0xb6, 0x1f, 0xdf, 0x89,
	0xaf, 0x6b, 0x2a, 0xf6, 0xda, 0xfa, 0x0b, 0xc7, 0x67, 0xeb, 0xb5, 0x74, 0x96, 0x45, 0x76, 0x60,
	0x49, 0x63, 0x35, 0x2c, 0x51, 0x33, 0xa7, 0xa3, 0x1f, 0x1b, 0xc8, 0xe9, 0xd9, 0xfa, 0xfd, 0x7d,
	0xae, 0xc7, 0x93, 0x51, 0x4c, 0x65, 0xde, 0xf3, 0xcd, 0xbb, 0xcf, 0x43, 0x95, 0x1d, 0xf4, 0xf4,
	0x51, 0xc1, 0x54, 0xfc, 0x82, 0xd1, 0xb4, 0xa5, 0xb1, 0x4a, 0x51, 0x33, 0xf2, 0xcc, 0x51, 0x51,
	0x2c, 0x54, 0xb7, 0x61, 0xc5, 0xdc, 0xbe, 0x5e, 0xcc, 0x1e, 0x56, 0x09, 0x16, 0x5e, 0x8b, 0x49,
	0x4f, 0xb0, 0x50, 0xe4, 0x15, 0x2c, 0x8f, 0x26, 0xa5, 0x70, 0x52, 0x16, 0xe6, 0x92, 0xb2, 0x64,
	0x08, 0x8c, 0x96, 0xe8, 0x1d, 0x34, 0x5d, 0x15, 0xb2, 0x0a, 0x8b, 0x19, 0x13, 0x32, 0xf7, 0xc7,
	0xe0, 0x02, 0xf2, 0x1c, 0x1a, 0x09, 0x16, 0x73, 0x74, 0xbc, 0x23, 0x74, 0x6a, 0x52, 0xa3, 0x8f,
	0x75, 0xe8, 0xec, 0xb9, 0xce, 0x5f, 0xf3, 0x9c, 0x6b, 0x6b, 0xa5, 0xd1, 0x3e, 0xcc, 0xb9, 0x70,
	0xc5, 0x6e, 0x6e, 0xa5, 0xc9, 0xdf, 0xe5, 0x82, 0x0c, 0x60, 0x65, 0x7a, 0x2a, 0xc3, 0x1c, 0xab,
	0x39, 0x4f, 0x06, 0xfc, 0xc9, 0xec, 0x62, 0x45, 0x52, 0xe8, 0x5c, 0xba, 0x6b, 0x29, 0x1b, 0x73,
	0x51, 0xb6, 0xa7, 0x0e, 0xef, 0x62, 0x15, 0x9d, 0x06, 0xf0, 0x5f, 0x22, 0x0f, 0x0f, 0x19, 0xd5,
	0x5c, 0x8a, 0x01, 0x2b, 0xb9, 0xcc, 0xc8, 0xff, 0xd0, 0x2c, 0xec, 0xca, 0x7a, 0xb0, 0x90, 0xfa,
	0x88, 0x14, 0xd0, 0xb1, 0xd3, 0xe1, 0xf0, 0x2c, 0xeb, 0xd6, 0xed, 0x88, 0xdc, 0x8a, 0x5d, 0x9d,
	0xd8, 0x5c, 0xac, 0xd9, 0xb8, 0x4a, 0x2e, 0xfa, 0x8f, 0x8c, 0xb6, 0xaf, 0xdf, 0xd7, 0x37, 0xff,
	0x40, 0x9b, 0x49, 0x50, 0xa9, 0x31, 0x2d, 0x99, 0x16, 0x20, 0x4f, 0xa1, 0x55, 0xe0, 0x91, 0x9c,
	0xe8, 0xdf, 0x8c, 0xe3, 0xc0, 0x82, 0xa6, 0xe3, 0xe8, 0x53, 0xa2, 0xcf, 0x81, 0xb9, 0x66, 0x66,
	0x4d, 0xee, 0x41, 0xa7, 0x64, 0x94, 0x17, 0x9c, 0x09, 0x8d, 0x59, 0x56, 0xfa, 0x51, 0xfa, 0x75,
	0x93, 0x20, 0x2c, 0x9a, 0xf7, 0x40, 0xfd, 0x8b, 0xc6, 0x1c, 0x73, 0xf4, 0x01, 0xda, 0x7b, 0x58,
	0x0d, 0x4a, 0x49, 0x19, 0xcb, 0x14, 0x11, 0x6e, 0x4a, 0x0a, 0x1f, 0xfb, 0x17, 0xe0, 0xaf, 0x16,
	0x6e, 0xeb, 0x59, 0xbd, 0xe8, 0x25, 0xb4, 0x9c, 0x23, 0xea, 0xaa, 0xb7, 0xc1, 0x8d, 0xbd, 0xed,
	0x27, 0xc7, 0xe7, 0x61, 0x70, 0x72, 0x1e, 0x06, 0x3f, 0xce, 0xc3, 0xe0, 0xd3, 0x45, 0x58, 0x3b,
	0xb9, 0x08, 0x6b, 0xdf, 0x2e, 0xc2, 0xda, 0xdb, 0x07, 0x57, 0x94, 0x19, 0x42, 0x3a, 0x46, 0x2e,
	0xec, 0xaa, 0x57, 0x5d, 0xbe, 0xe6, 0x56, 0xe0, 0xa8, 0x69, 0x1f, 0xde, 0x27, 0x3f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x12, 0x33, 0x0f, 0xa0, 0xea, 0x05, 0x00, 0x00,
}

func (m *Charity) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Charity) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Charity) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Checksum) > 0 {
		i -= len(m.Checksum)
		copy(dAtA[i:], m.Checksum)
		i = encodeVarintCharity(dAtA, i, uint64(len(m.Checksum)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AccAddress) > 0 {
		i -= len(m.AccAddress)
		copy(dAtA[i:], m.AccAddress)
		i = encodeVarintCharity(dAtA, i, uint64(len(m.AccAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.CharityName) > 0 {
		i -= len(m.CharityName)
		copy(dAtA[i:], m.CharityName)
		i = encodeVarintCharity(dAtA, i, uint64(len(m.CharityName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.BurnRate.Size()
		i -= size
		if _, err := m.BurnRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCharity(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.TaxCaps) > 0 {
		for iNdEx := len(m.TaxCaps) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TaxCaps[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCharity(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size := m.TaxRate.Size()
		i -= size
		if _, err := m.TaxRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCharity(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Charities) > 0 {
		for iNdEx := len(m.Charities) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Charities[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCharity(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *TaxCap) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaxCap) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TaxCap) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Cap.Size()
		i -= size
		if _, err := m.Cap.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCharity(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintCharity(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TaxRateLimits) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaxRateLimits) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TaxRateLimits) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.BurnRateMax.Size()
		i -= size
		if _, err := m.BurnRateMax.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCharity(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.TaxRateMax.Size()
		i -= size
		if _, err := m.TaxRateMax.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCharity(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.RateMin.Size()
		i -= size
		if _, err := m.RateMin.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCharity(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *CollectionPeriod) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CollectionPeriod) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CollectionPeriod) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Payouts) > 0 {
		for iNdEx := len(m.Payouts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Payouts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCharity(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.TaxCollected) > 0 {
		for iNdEx := len(m.TaxCollected) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TaxCollected[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCharity(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Period != 0 {
		i = encodeVarintCharity(dAtA, i, uint64(m.Period))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Payout) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Payout) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Payout) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Coins) > 0 {
		for iNdEx := len(m.Coins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Coins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCharity(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Recipientaddr) > 0 {
		i -= len(m.Recipientaddr)
		copy(dAtA[i:], m.Recipientaddr)
		i = encodeVarintCharity(dAtA, i, uint64(len(m.Recipientaddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TaxProceeds) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaxProceeds) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TaxProceeds) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TaxProceeds) > 0 {
		for iNdEx := len(m.TaxProceeds) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TaxProceeds[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCharity(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Payouts) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Payouts) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Payouts) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Payouts) > 0 {
		for iNdEx := len(m.Payouts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Payouts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCharity(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintCharity(dAtA []byte, offset int, v uint64) int {
	offset -= sovCharity(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Charity) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CharityName)
	if l > 0 {
		n += 1 + l + sovCharity(uint64(l))
	}
	l = len(m.AccAddress)
	if l > 0 {
		n += 1 + l + sovCharity(uint64(l))
	}
	l = len(m.Checksum)
	if l > 0 {
		n += 1 + l + sovCharity(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Charities) > 0 {
		for _, e := range m.Charities {
			l = e.Size()
			n += 1 + l + sovCharity(uint64(l))
		}
	}
	l = m.TaxRate.Size()
	n += 1 + l + sovCharity(uint64(l))
	if len(m.TaxCaps) > 0 {
		for _, e := range m.TaxCaps {
			l = e.Size()
			n += 1 + l + sovCharity(uint64(l))
		}
	}
	l = m.BurnRate.Size()
	n += 1 + l + sovCharity(uint64(l))
	return n
}

func (m *TaxCap) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovCharity(uint64(l))
	}
	l = m.Cap.Size()
	n += 1 + l + sovCharity(uint64(l))
	return n
}

func (m *TaxRateLimits) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.RateMin.Size()
	n += 1 + l + sovCharity(uint64(l))
	l = m.TaxRateMax.Size()
	n += 1 + l + sovCharity(uint64(l))
	l = m.BurnRateMax.Size()
	n += 1 + l + sovCharity(uint64(l))
	return n
}

func (m *CollectionPeriod) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Period != 0 {
		n += 1 + sovCharity(uint64(m.Period))
	}
	if len(m.TaxCollected) > 0 {
		for _, e := range m.TaxCollected {
			l = e.Size()
			n += 1 + l + sovCharity(uint64(l))
		}
	}
	if len(m.Payouts) > 0 {
		for _, e := range m.Payouts {
			l = e.Size()
			n += 1 + l + sovCharity(uint64(l))
		}
	}
	return n
}

func (m *Payout) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Recipientaddr)
	if l > 0 {
		n += 1 + l + sovCharity(uint64(l))
	}
	if len(m.Coins) > 0 {
		for _, e := range m.Coins {
			l = e.Size()
			n += 1 + l + sovCharity(uint64(l))
		}
	}
	return n
}

func (m *TaxProceeds) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TaxProceeds) > 0 {
		for _, e := range m.TaxProceeds {
			l = e.Size()
			n += 1 + l + sovCharity(uint64(l))
		}
	}
	return n
}

func (m *Payouts) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Payouts) > 0 {
		for _, e := range m.Payouts {
			l = e.Size()
			n += 1 + l + sovCharity(uint64(l))
		}
	}
	return n
}

func sovCharity(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCharity(x uint64) (n int) {
	return sovCharity(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Charity) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCharity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Charity: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Charity: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CharityName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCharity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCharity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CharityName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCharity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCharity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checksum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCharity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCharity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Checksum = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCharity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCharity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCharity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Charities", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCharity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCharity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Charities = append(m.Charities, Charity{})
			if err := m.Charities[len(m.Charities)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaxRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCharity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCharity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TaxRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaxCaps", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCharity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCharity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaxCaps = append(m.TaxCaps, TaxCap{})
			if err := m.TaxCaps[len(m.TaxCaps)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCharity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCharity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BurnRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCharity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCharity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TaxCap) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCharity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaxCap: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaxCap: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCharity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCharity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCharity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCharity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Cap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCharity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCharity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TaxRateLimits) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCharity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaxRateLimits: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaxRateLimits: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateMin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCharity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCharity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RateMin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaxRateMax", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCharity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCharity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TaxRateMax.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnRateMax", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCharity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCharity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BurnRateMax.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCharity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCharity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CollectionPeriod) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCharity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CollectionPeriod: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CollectionPeriod: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Period", wireType)
			}
			m.Period = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Period |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaxCollected", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCharity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCharity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaxCollected = append(m.TaxCollected, types.Coin{})
			if err := m.TaxCollected[len(m.TaxCollected)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payouts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCharity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCharity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payouts = append(m.Payouts, Payout{})
			if err := m.Payouts[len(m.Payouts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCharity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCharity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Payout) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCharity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Payout: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Payout: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipientaddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCharity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCharity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipientaddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCharity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCharity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Coins = append(m.Coins, types.Coin{})
			if err := m.Coins[len(m.Coins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCharity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCharity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TaxProceeds) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCharity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaxProceeds: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaxProceeds: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaxProceeds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCharity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCharity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaxProceeds = append(m.TaxProceeds, types.Coin{})
			if err := m.TaxProceeds[len(m.TaxProceeds)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCharity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCharity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Payouts) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCharity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Payouts: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Payouts: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payouts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCharity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCharity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payouts = append(m.Payouts, Payout{})
			if err := m.Payouts[len(m.Payouts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCharity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCharity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCharity(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCharity
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCharity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCharity
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCharity
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCharity
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCharity        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCharity          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCharity = fmt.Errorf("proto: unexpected end of group")
)
