// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: charity/genesis.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the charity module's genesis state.
type GenesisState struct {
	// this line is used by starport scaffolding # genesis/proto/state
	// this line is used by starport scaffolding # ibc/genesis/proto
	Params        Params        `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	TaxRateLimits TaxRateLimits `protobuf:"bytes,2,opt,name=tax_rate_limits,json=taxRateLimits,proto3" json:"tax_rate_limits"`
	// Current amount of tax collected during current collection period
	TaxProceeds       github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=tax_proceeds,json=taxProceeds,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"tax_proceeds"`
	CollectionPeriods []CollectionPeriod                     `protobuf:"bytes,4,rep,name=collection_periods,json=collectionPeriods,proto3" json:"collection_periods"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a8c5ac700ef3705, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetTaxRateLimits() TaxRateLimits {
	if m != nil {
		return m.TaxRateLimits
	}
	return TaxRateLimits{}
}

func (m *GenesisState) GetCollectionPeriods() []CollectionPeriod {
	if m != nil {
		return m.CollectionPeriods
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "user.encichain.charity.GenesisState")
}

func init() { proto.RegisterFile("charity/genesis.proto", fileDescriptor_7a8c5ac700ef3705) }

var fileDescriptor_7a8c5ac700ef3705 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0x93, 0xb6, 0x14, 0xbe, 0xb4, 0x1f, 0x62, 0x50, 0x09, 0x3d, 0x6c, 0x8b, 0xa0, 0xc4,
	0x83, 0x1b, 0xa8, 0x57, 0x4f, 0xed, 0x41, 0x04, 0x0f, 0xb5, 0xf5, 0x24, 0x48, 0xd9, 0x6e, 0x97,
	0x74, 0xb1, 0xc9, 0x86, 0x9d, 0x29, 0xa4, 0xff, 0xc2, 0x9f, 0xd5, 0x63, 0xc1, 0x8b, 0x78, 0x28,
	0xd2, 0xfe, 0x11, 0x49, 0xb2, 0x86, 0x22, 0xf6, 0xb4, 0xcb, 0xf0, 0xcc, 0xf3, 0xbe, 0x30, 0xce,
	0x29, 0x9f, 0x31, 0x2d, 0x71, 0x19, 0x84, 0x22, 0x16, 0x20, 0x81, 0x26, 0x5a, 0xa1, 0x72, 0xcf,
	0x16, 0x20, 0x34, 0x15, 0x31, 0x97, 0x7c, 0xc6, 0x64, 0x4c, 0x0d, 0xd5, 0x3a, 0x09, 0x55, 0xa8,
	0x72, 0x24, 0xc8, 0x7e, 0x05, 0xdd, 0x2a, 0x25, 0xe6, 0x2d, 0xc6, 0xe7, 0xef, 0x15, 0xa7, 0x79,
	0x57, 0x68, 0x47, 0xc8, 0x50, 0xb8, 0xb7, 0x4e, 0x3d, 0x61, 0x9a, 0x45, 0xe0, 0xd9, 0x1d, 0xdb,
	0x6f, 0x74, 0x09, 0xfd, 0x3b, 0x86, 0x0e, 0x72, 0xaa, 0x57, 0x5b, 0x6d, 0xda, 0xd6, 0xd0, 0xec,
	0xb8, 0x23, 0xe7, 0x08, 0x59, 0x3a, 0xd6, 0x0c, 0xc5, 0x78, 0x2e, 0x23, 0x89, 0xe0, 0x55, 0x72,
	0xcd, 0xc5, 0x21, 0xcd, 0x13, 0x4b, 0x87, 0x0c, 0xc5, 0x43, 0x0e, 0x1b, 0xdb, 0x7f, 0xdc, 0x1f,
	0xba, 0x8f, 0x4e, 0x33, 0x93, 0x26, 0x5a, 0x71, 0x21, 0xa6, 0xe0, 0x55, 0x3b, 0xb6, 0xff, 0xaf,
	0x47, 0x33, 0xf4, 0x73, 0xd3, 0xbe, 0x0c, 0x25, 0xce, 0x16, 0x13, 0xca, 0x55, 0x14, 0x70, 0x05,
	0x91, 0x02, 0xf3, 0x5c, 0xc3, 0xf4, 0x35, 0xc0, 0x65, 0x22, 0x80, 0xde, 0xc7, 0x38, 0x6c, 0x20,
	0x4b, 0x07, 0x46, 0xe1, 0xbe, 0x38, 0x2e, 0x57, 0xf3, 0xb9, 0xe0, 0x28, 0x55, 0x3c, 0x4e, 0x84,
	0x96, 0x6a, 0x0a, 0x5e, 0xad, 0x53, 0xf5, 0x1b, 0x5d, 0xff, 0x50, 0xd5, 0x7e, 0xb9, 0x31, 0xc8,
	0x17, 0x4c, 0xdb, 0x63, 0xfe, 0x6b, 0x0e, 0xbd, 0xfe, 0x6a, 0x4b, 0xec, 0xf5, 0x96, 0xd8, 0x5f,
	0x5b, 0x62, 0xbf, 0xed, 0x88, 0xb5, 0xde, 0x11, 0xeb, 0x63, 0x47, 0xac, 0xe7, 0xab, 0xbd, 0xb6,
	0x59, 0x4c, 0x50, 0xc6, 0x04, 0xe9, 0xcf, 0x69, 0x8a, 0xd2, 0x93, 0x7a, 0x7e, 0xa1, 0x9b, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xdf, 0x07, 0x33, 0xff, 0x01, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CollectionPeriods) > 0 {
		for iNdEx := len(m.CollectionPeriods) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CollectionPeriods[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size := m.TaxProceeds.Size()
		i -= size
		if _, err := m.TaxProceeds.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.TaxRateLimits.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.TaxRateLimits.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.TaxProceeds.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.CollectionPeriods) > 0 {
		for _, e := range m.CollectionPeriods {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaxRateLimits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TaxRateLimits.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaxProceeds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TaxProceeds.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionPeriods", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollectionPeriods = append(m.CollectionPeriods, CollectionPeriod{})
			if err := m.CollectionPeriods[len(m.CollectionPeriods)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
