// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: charity/query.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryTaxRateRequest is the request type for the Query TaxRate Request RPC method
type QueryTaxRateRequest struct {
}

func (m *QueryTaxRateRequest) Reset()         { *m = QueryTaxRateRequest{} }
func (m *QueryTaxRateRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTaxRateRequest) ProtoMessage()    {}
func (*QueryTaxRateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd4bd1d3aa6ffcce, []int{0}
}
func (m *QueryTaxRateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTaxRateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTaxRateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTaxRateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTaxRateRequest.Merge(m, src)
}
func (m *QueryTaxRateRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTaxRateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTaxRateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTaxRateRequest proto.InternalMessageInfo

// QueryTaxRateResponse is the response type for the Query TaxRate Request RPC method
type QueryTaxRateResponse struct {
	TaxRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=tax_rate,json=taxRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"tax_rate"`
}

func (m *QueryTaxRateResponse) Reset()         { *m = QueryTaxRateResponse{} }
func (m *QueryTaxRateResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTaxRateResponse) ProtoMessage()    {}
func (*QueryTaxRateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd4bd1d3aa6ffcce, []int{1}
}
func (m *QueryTaxRateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTaxRateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTaxRateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTaxRateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTaxRateResponse.Merge(m, src)
}
func (m *QueryTaxRateResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTaxRateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTaxRateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTaxRateResponse proto.InternalMessageInfo

// QueryParamsRequest is the request type for the Query Params Request RPC method
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd4bd1d3aa6ffcce, []int{2}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query Params Request RPC method
type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd4bd1d3aa6ffcce, []int{3}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryCharityRequest is the request type for the Query Charity Request RPC method
type QueryCharityRequest struct {
}

func (m *QueryCharityRequest) Reset()         { *m = QueryCharityRequest{} }
func (m *QueryCharityRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCharityRequest) ProtoMessage()    {}
func (*QueryCharityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd4bd1d3aa6ffcce, []int{4}
}
func (m *QueryCharityRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCharityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCharityRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCharityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCharityRequest.Merge(m, src)
}
func (m *QueryCharityRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCharityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCharityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCharityRequest proto.InternalMessageInfo

// QueryCharityResponse is the response type for the Query Charity Request RPC method
type QueryCharityResponse struct {
	Charity Charity `protobuf:"bytes,1,opt,name=charity,proto3" json:"charity"`
}

func (m *QueryCharityResponse) Reset()         { *m = QueryCharityResponse{} }
func (m *QueryCharityResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCharityResponse) ProtoMessage()    {}
func (*QueryCharityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd4bd1d3aa6ffcce, []int{5}
}
func (m *QueryCharityResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCharityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCharityResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCharityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCharityResponse.Merge(m, src)
}
func (m *QueryCharityResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCharityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCharityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCharityResponse proto.InternalMessageInfo

func (m *QueryCharityResponse) GetCharity() Charity {
	if m != nil {
		return m.Charity
	}
	return Charity{}
}

// QueryTaxCapRequest is the request type for the Query TaxCap Request RPC method
type QueryTaxCapRequest struct {
}

func (m *QueryTaxCapRequest) Reset()         { *m = QueryTaxCapRequest{} }
func (m *QueryTaxCapRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTaxCapRequest) ProtoMessage()    {}
func (*QueryTaxCapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd4bd1d3aa6ffcce, []int{6}
}
func (m *QueryTaxCapRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTaxCapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTaxCapRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTaxCapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTaxCapRequest.Merge(m, src)
}
func (m *QueryTaxCapRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTaxCapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTaxCapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTaxCapRequest proto.InternalMessageInfo

// QueryTaxCapResponse is the response type for the Query TaxCap Request RPC method
type QueryTaxCapResponse struct {
	TaxCap github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=tax_cap,json=taxCap,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"tax_cap"`
}

func (m *QueryTaxCapResponse) Reset()         { *m = QueryTaxCapResponse{} }
func (m *QueryTaxCapResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTaxCapResponse) ProtoMessage()    {}
func (*QueryTaxCapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd4bd1d3aa6ffcce, []int{7}
}
func (m *QueryTaxCapResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTaxCapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTaxCapResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTaxCapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTaxCapResponse.Merge(m, src)
}
func (m *QueryTaxCapResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTaxCapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTaxCapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTaxCapResponse proto.InternalMessageInfo

// QueryTaxRateLimitsRequest is the request type for the Query TaxRateLimits Request RPC method
type QueryTaxRateLimitsRequest struct {
}

func (m *QueryTaxRateLimitsRequest) Reset()         { *m = QueryTaxRateLimitsRequest{} }
func (m *QueryTaxRateLimitsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTaxRateLimitsRequest) ProtoMessage()    {}
func (*QueryTaxRateLimitsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd4bd1d3aa6ffcce, []int{8}
}
func (m *QueryTaxRateLimitsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTaxRateLimitsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTaxRateLimitsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTaxRateLimitsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTaxRateLimitsRequest.Merge(m, src)
}
func (m *QueryTaxRateLimitsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTaxRateLimitsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTaxRateLimitsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTaxRateLimitsRequest proto.InternalMessageInfo

// QueryTaxRateLimitsResponse is the response type for the Query TaxRateLimits Request RPC method
type QueryTaxRateLimitsResponse struct {
	TaxRateLimits TaxRateLimits `protobuf:"bytes,1,opt,name=tax_rate_limits,json=taxRateLimits,proto3" json:"tax_rate_limits"`
}

func (m *QueryTaxRateLimitsResponse) Reset()         { *m = QueryTaxRateLimitsResponse{} }
func (m *QueryTaxRateLimitsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTaxRateLimitsResponse) ProtoMessage()    {}
func (*QueryTaxRateLimitsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd4bd1d3aa6ffcce, []int{9}
}
func (m *QueryTaxRateLimitsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTaxRateLimitsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTaxRateLimitsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTaxRateLimitsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTaxRateLimitsResponse.Merge(m, src)
}
func (m *QueryTaxRateLimitsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTaxRateLimitsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTaxRateLimitsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTaxRateLimitsResponse proto.InternalMessageInfo

func (m *QueryTaxRateLimitsResponse) GetTaxRateLimits() TaxRateLimits {
	if m != nil {
		return m.TaxRateLimits
	}
	return TaxRateLimits{}
}

// QueryCollectionPeriodsRequest is the request type for the Query CollectionPeriods Request RPC method
type QueryCollectionPeriodsRequest struct {
}

func (m *QueryCollectionPeriodsRequest) Reset()         { *m = QueryCollectionPeriodsRequest{} }
func (m *QueryCollectionPeriodsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCollectionPeriodsRequest) ProtoMessage()    {}
func (*QueryCollectionPeriodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd4bd1d3aa6ffcce, []int{10}
}
func (m *QueryCollectionPeriodsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCollectionPeriodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCollectionPeriodsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCollectionPeriodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCollectionPeriodsRequest.Merge(m, src)
}
func (m *QueryCollectionPeriodsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCollectionPeriodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCollectionPeriodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCollectionPeriodsRequest proto.InternalMessageInfo

// QueryCollectionPeriodsResponse is the response type for the Query CollectionPeriods Request RPC method
type QueryCollectionPeriodsResponse struct {
	CollectionPeriods []CollectionPeriod `protobuf:"bytes,1,rep,name=collection_periods,json=collectionPeriods,proto3" json:"collection_periods"`
}

func (m *QueryCollectionPeriodsResponse) Reset()         { *m = QueryCollectionPeriodsResponse{} }
func (m *QueryCollectionPeriodsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCollectionPeriodsResponse) ProtoMessage()    {}
func (*QueryCollectionPeriodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd4bd1d3aa6ffcce, []int{11}
}
func (m *QueryCollectionPeriodsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCollectionPeriodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCollectionPeriodsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCollectionPeriodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCollectionPeriodsResponse.Merge(m, src)
}
func (m *QueryCollectionPeriodsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCollectionPeriodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCollectionPeriodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCollectionPeriodsResponse proto.InternalMessageInfo

func (m *QueryCollectionPeriodsResponse) GetCollectionPeriods() []CollectionPeriod {
	if m != nil {
		return m.CollectionPeriods
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryTaxRateRequest)(nil), "user.encichain.charity.QueryTaxRateRequest")
	proto.RegisterType((*QueryTaxRateResponse)(nil), "user.encichain.charity.QueryTaxRateResponse")
	proto.RegisterType((*QueryParamsRequest)(nil), "user.encichain.charity.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "user.encichain.charity.QueryParamsResponse")
	proto.RegisterType((*QueryCharityRequest)(nil), "user.encichain.charity.QueryCharityRequest")
	proto.RegisterType((*QueryCharityResponse)(nil), "user.encichain.charity.QueryCharityResponse")
	proto.RegisterType((*QueryTaxCapRequest)(nil), "user.encichain.charity.QueryTaxCapRequest")
	proto.RegisterType((*QueryTaxCapResponse)(nil), "user.encichain.charity.QueryTaxCapResponse")
	proto.RegisterType((*QueryTaxRateLimitsRequest)(nil), "user.encichain.charity.QueryTaxRateLimitsRequest")
	proto.RegisterType((*QueryTaxRateLimitsResponse)(nil), "user.encichain.charity.QueryTaxRateLimitsResponse")
	proto.RegisterType((*QueryCollectionPeriodsRequest)(nil), "user.encichain.charity.QueryCollectionPeriodsRequest")
	proto.RegisterType((*QueryCollectionPeriodsResponse)(nil), "user.encichain.charity.QueryCollectionPeriodsResponse")
}

func init() { proto.RegisterFile("charity/query.proto", fileDescriptor_fd4bd1d3aa6ffcce) }

var fileDescriptor_fd4bd1d3aa6ffcce = []byte{
	// 651 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x4f, 0x6b, 0x13, 0x41,
	0x14, 0xcf, 0xfa, 0x67, 0xab, 0x53, 0x8a, 0x74, 0xda, 0x6a, 0xbb, 0xad, 0x9b, 0xb8, 0x68, 0x89,
	0xb6, 0xee, 0x62, 0x44, 0x4f, 0x82, 0x90, 0x08, 0x52, 0xf0, 0x50, 0xd3, 0x82, 0x20, 0x68, 0x98,
	0x4e, 0x87, 0x64, 0x31, 0xd9, 0xd9, 0xec, 0x4e, 0x20, 0x39, 0x09, 0xc5, 0x83, 0x47, 0xc1, 0x2f,
	0xe0, 0x47, 0xf0, 0x63, 0xf4, 0x58, 0xf0, 0x22, 0x1e, 0x8a, 0x24, 0x7e, 0x0f, 0x65, 0x67, 0xde,
	0x6e, 0xb3, 0x69, 0x36, 0x49, 0x3d, 0xcd, 0xf2, 0xe6, 0xbd, 0xf7, 0xfb, 0xbd, 0x3f, 0xbf, 0x59,
	0xb4, 0x44, 0x1b, 0x24, 0x70, 0x45, 0xcf, 0x69, 0x77, 0x58, 0xd0, 0xb3, 0xfd, 0x80, 0x0b, 0x8e,
	0x6f, 0x76, 0x42, 0x16, 0xd8, 0xcc, 0xa3, 0x2e, 0x6d, 0x10, 0xd7, 0xb3, 0xc1, 0xc7, 0xd8, 0xa8,
	0x73, 0x5e, 0x6f, 0x32, 0x87, 0xf8, 0xae, 0x43, 0x3c, 0x8f, 0x0b, 0x22, 0x5c, 0xee, 0x85, 0x2a,
	0xca, 0x58, 0xae, 0xf3, 0x3a, 0x97, 0x9f, 0x4e, 0xf4, 0x05, 0xd6, 0x95, 0x18, 0x00, 0x4e, 0x65,
	0xb6, 0x56, 0xd0, 0xd2, 0xeb, 0x08, 0x71, 0x9f, 0x74, 0xab, 0x44, 0xb0, 0x2a, 0x6b, 0x77, 0x58,
	0x28, 0x2c, 0x82, 0x96, 0xd3, 0xe6, 0xd0, 0xe7, 0x5e, 0xc8, 0xf0, 0x0e, 0xba, 0x26, 0x48, 0xb7,
	0x16, 0x10, 0xc1, 0x56, 0xb5, 0x82, 0x56, 0xbc, 0x5e, 0xb6, 0x8f, 0x4f, 0xf3, 0xb9, 0x5f, 0xa7,
	0xf9, 0xcd, 0xba, 0x2b, 0x1a, 0x9d, 0x03, 0x9b, 0xf2, 0x96, 0x43, 0x79, 0xd8, 0xe2, 0x21, 0x1c,
	0x0f, 0xc3, 0xc3, 0x0f, 0x8e, 0xe8, 0xf9, 0x2c, 0xb4, 0x5f, 0x30, 0x5a, 0x9d, 0x13, 0x2a, 0xa5,
	0xb5, 0x8c, 0xb0, 0x84, 0xd8, 0x25, 0x01, 0x69, 0x85, 0x31, 0xf0, 0x1e, 0xf0, 0x89, 0xad, 0x80,
	0xfb, 0x0c, 0xe9, 0xbe, 0xb4, 0x48, 0xd4, 0xf9, 0x92, 0x69, 0x8f, 0x6f, 0x8d, 0xad, 0xe2, 0xca,
	0x57, 0x22, 0x56, 0x55, 0x88, 0x49, 0x8a, 0xac, 0x28, 0xa7, 0x18, 0xeb, 0x0d, 0x14, 0x99, 0x98,
	0x01, 0xec, 0x39, 0x9a, 0x83, 0x74, 0x80, 0x96, 0xcf, 0x42, 0x83, 0x48, 0x80, 0x8b, 0xa3, 0x92,
	0xd2, 0xf6, 0x49, 0xb7, 0x42, 0xfc, 0x18, 0xee, 0xfd, 0x59, 0xab, 0xa5, 0x15, 0xd0, 0x5e, 0xa2,
	0xa8, 0x25, 0x35, 0x4a, 0xfc, 0xff, 0xe8, 0xe8, 0x8e, 0x27, 0xaa, 0xba, 0x90, 0x09, 0xad, 0x75,
	0xb4, 0x36, 0x3c, 0xb3, 0x57, 0x6e, 0xcb, 0x15, 0x49, 0x5f, 0xdb, 0xc8, 0x18, 0x77, 0x09, 0x1c,
	0xf6, 0xd0, 0x8d, 0x78, 0xac, 0xb5, 0xa6, 0xbc, 0x82, 0xca, 0xef, 0x65, 0x55, 0x9e, 0xca, 0x03,
	0xf5, 0x2f, 0x88, 0x61, 0xa3, 0x95, 0x47, 0xb7, 0x55, 0x7b, 0x79, 0xb3, 0xc9, 0x68, 0xb4, 0xa1,
	0xbb, 0x2c, 0x70, 0xf9, 0x61, 0xc2, 0xe9, 0x23, 0x32, 0xb3, 0x1c, 0x80, 0xd7, 0x3b, 0x84, 0x69,
	0x72, 0x59, 0xf3, 0xd5, 0xed, 0xaa, 0x56, 0xb8, 0x5c, 0x9c, 0x2f, 0x15, 0x33, 0x87, 0x32, 0x92,
	0x0e, 0xd8, 0x2d, 0xd2, 0x51, 0x98, 0xd2, 0x5f, 0x1d, 0x5d, 0x95, 0x0c, 0xf0, 0x91, 0x86, 0x74,
	0xb5, 0x3a, 0xf8, 0x41, 0x56, 0xde, 0xf3, 0xdb, 0x6a, 0x6c, 0xcd, 0xe4, 0xab, 0x8a, 0xb1, 0xf2,
	0x47, 0x3f, 0xfe, 0x7c, 0xbd, 0xb4, 0x86, 0x6f, 0x39, 0x23, 0x52, 0x74, 0xd4, 0x9a, 0xe2, 0xcf,
	0x1a, 0x9a, 0x83, 0xbe, 0xe2, 0xc9, 0x99, 0xd3, 0x6a, 0x35, 0xb6, 0x67, 0x73, 0x06, 0x1e, 0x96,
	0xe4, 0xb1, 0x81, 0x0d, 0x27, 0x09, 0x48, 0x98, 0x08, 0xd2, 0x8d, 0x96, 0x40, 0x52, 0x81, 0xe5,
	0x9e, 0x42, 0x25, 0xad, 0xa9, 0x29, 0x54, 0x46, 0x94, 0x36, 0x91, 0x0a, 0x9c, 0xf8, 0x93, 0x86,
	0x74, 0x25, 0x99, 0x29, 0xa3, 0x49, 0xa9, 0xcd, 0xd8, 0x9a, 0xc9, 0x17, 0x78, 0xdc, 0x91, 0x3c,
	0xd6, 0xf1, 0xda, 0xf8, 0x96, 0x50, 0xe2, 0xe3, 0x6f, 0x1a, 0x5a, 0x48, 0x2d, 0x3d, 0x7e, 0x34,
	0x4b, 0xd7, 0x53, 0x2a, 0x34, 0x4a, 0x17, 0x09, 0x01, 0x6e, 0x45, 0xc9, 0xcd, 0xc2, 0x85, 0xec,
	0x71, 0x29, 0xc9, 0xe2, 0xef, 0x1a, 0x5a, 0x3c, 0xa7, 0x25, 0xfc, 0x64, 0xf2, 0x44, 0x32, 0xc4,
	0x69, 0x3c, 0xbd, 0x68, 0x18, 0xd0, 0xdd, 0x96, 0x74, 0x37, 0xf1, 0xdd, 0x71, 0x23, 0x4d, 0xa2,
	0x40, 0xca, 0xe5, 0xca, 0x71, 0xdf, 0xd4, 0x4e, 0xfa, 0xa6, 0xf6, 0xbb, 0x6f, 0x6a, 0x5f, 0x06,
	0x66, 0xee, 0x64, 0x60, 0xe6, 0x7e, 0x0e, 0xcc, 0xdc, 0xdb, 0xfb, 0x43, 0xaf, 0x5f, 0xc4, 0x64,
	0x28, 0x5d, 0xf7, 0xac, 0xfe, 0xe8, 0x11, 0x3c, 0xd0, 0xe5, 0xaf, 0xec, 0xf1, 0xbf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xdc, 0x95, 0x5d, 0x67, 0x44, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns all params
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// TaxRate returns the set tax rate
	TaxRate(ctx context.Context, in *QueryTaxRateRequest, opts ...grpc.CallOption) (*QueryTaxRateResponse, error)
	// Charity returns the set charity
	Charity(ctx context.Context, in *QueryCharityRequest, opts ...grpc.CallOption) (*QueryCharityResponse, error)
	// TaxCap returns the tax cap amount
	TaxCap(ctx context.Context, in *QueryTaxCapRequest, opts ...grpc.CallOption) (*QueryTaxCapResponse, error)
	// TaxRateLimits returns the tax rate limits
	TaxRateLimits(ctx context.Context, in *QueryTaxRateLimitsRequest, opts ...grpc.CallOption) (*QueryTaxRateLimitsResponse, error)
	// CollectionPeriods returns the list of collection periods
	CollectionPeriods(ctx context.Context, in *QueryCollectionPeriodsRequest, opts ...grpc.CallOption) (*QueryCollectionPeriodsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/user.encichain.charity.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TaxRate(ctx context.Context, in *QueryTaxRateRequest, opts ...grpc.CallOption) (*QueryTaxRateResponse, error) {
	out := new(QueryTaxRateResponse)
	err := c.cc.Invoke(ctx, "/user.encichain.charity.Query/TaxRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Charity(ctx context.Context, in *QueryCharityRequest, opts ...grpc.CallOption) (*QueryCharityResponse, error) {
	out := new(QueryCharityResponse)
	err := c.cc.Invoke(ctx, "/user.encichain.charity.Query/Charity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TaxCap(ctx context.Context, in *QueryTaxCapRequest, opts ...grpc.CallOption) (*QueryTaxCapResponse, error) {
	out := new(QueryTaxCapResponse)
	err := c.cc.Invoke(ctx, "/user.encichain.charity.Query/TaxCap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TaxRateLimits(ctx context.Context, in *QueryTaxRateLimitsRequest, opts ...grpc.CallOption) (*QueryTaxRateLimitsResponse, error) {
	out := new(QueryTaxRateLimitsResponse)
	err := c.cc.Invoke(ctx, "/user.encichain.charity.Query/TaxRateLimits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CollectionPeriods(ctx context.Context, in *QueryCollectionPeriodsRequest, opts ...grpc.CallOption) (*QueryCollectionPeriodsResponse, error) {
	out := new(QueryCollectionPeriodsResponse)
	err := c.cc.Invoke(ctx, "/user.encichain.charity.Query/CollectionPeriods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params returns all params
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// TaxRate returns the set tax rate
	TaxRate(context.Context, *QueryTaxRateRequest) (*QueryTaxRateResponse, error)
	// Charity returns the set charity
	Charity(context.Context, *QueryCharityRequest) (*QueryCharityResponse, error)
	// TaxCap returns the tax cap amount
	TaxCap(context.Context, *QueryTaxCapRequest) (*QueryTaxCapResponse, error)
	// TaxRateLimits returns the tax rate limits
	TaxRateLimits(context.Context, *QueryTaxRateLimitsRequest) (*QueryTaxRateLimitsResponse, error)
	// CollectionPeriods returns the list of collection periods
	CollectionPeriods(context.Context, *QueryCollectionPeriodsRequest) (*QueryCollectionPeriodsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) TaxRate(ctx context.Context, req *QueryTaxRateRequest) (*QueryTaxRateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaxRate not implemented")
}
func (*UnimplementedQueryServer) Charity(ctx context.Context, req *QueryCharityRequest) (*QueryCharityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Charity not implemented")
}
func (*UnimplementedQueryServer) TaxCap(ctx context.Context, req *QueryTaxCapRequest) (*QueryTaxCapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaxCap not implemented")
}
func (*UnimplementedQueryServer) TaxRateLimits(ctx context.Context, req *QueryTaxRateLimitsRequest) (*QueryTaxRateLimitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaxRateLimits not implemented")
}
func (*UnimplementedQueryServer) CollectionPeriods(ctx context.Context, req *QueryCollectionPeriodsRequest) (*QueryCollectionPeriodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectionPeriods not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.encichain.charity.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TaxRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTaxRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TaxRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.encichain.charity.Query/TaxRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TaxRate(ctx, req.(*QueryTaxRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Charity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCharityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Charity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.encichain.charity.Query/Charity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Charity(ctx, req.(*QueryCharityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TaxCap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTaxCapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TaxCap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.encichain.charity.Query/TaxCap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TaxCap(ctx, req.(*QueryTaxCapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TaxRateLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTaxRateLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TaxRateLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.encichain.charity.Query/TaxRateLimits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TaxRateLimits(ctx, req.(*QueryTaxRateLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CollectionPeriods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCollectionPeriodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CollectionPeriods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.encichain.charity.Query/CollectionPeriods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CollectionPeriods(ctx, req.(*QueryCollectionPeriodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.encichain.charity.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "TaxRate",
			Handler:    _Query_TaxRate_Handler,
		},
		{
			MethodName: "Charity",
			Handler:    _Query_Charity_Handler,
		},
		{
			MethodName: "TaxCap",
			Handler:    _Query_TaxCap_Handler,
		},
		{
			MethodName: "TaxRateLimits",
			Handler:    _Query_TaxRateLimits_Handler,
		},
		{
			MethodName: "CollectionPeriods",
			Handler:    _Query_CollectionPeriods_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "charity/query.proto",
}

func (m *QueryTaxRateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTaxRateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTaxRateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryTaxRateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTaxRateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTaxRateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TaxRate.Size()
		i -= size
		if _, err := m.TaxRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryCharityRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCharityRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCharityRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryCharityResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCharityResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCharityResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Charity.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryTaxCapRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTaxCapRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTaxCapRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryTaxCapResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTaxCapResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTaxCapResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TaxCap.Size()
		i -= size
		if _, err := m.TaxCap.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryTaxRateLimitsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTaxRateLimitsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTaxRateLimitsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryTaxRateLimitsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTaxRateLimitsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTaxRateLimitsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TaxRateLimits.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryCollectionPeriodsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCollectionPeriodsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCollectionPeriodsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryCollectionPeriodsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCollectionPeriodsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCollectionPeriodsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CollectionPeriods) > 0 {
		for iNdEx := len(m.CollectionPeriods) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CollectionPeriods[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryTaxRateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryTaxRateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TaxRate.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryCharityRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryCharityResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Charity.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryTaxCapRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryTaxCapResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TaxCap.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryTaxRateLimitsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryTaxRateLimitsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TaxRateLimits.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryCollectionPeriodsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryCollectionPeriodsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.CollectionPeriods) > 0 {
		for _, e := range m.CollectionPeriods {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryTaxRateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTaxRateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTaxRateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTaxRateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTaxRateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTaxRateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaxRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TaxRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCharityRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCharityRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCharityRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCharityResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCharityResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCharityResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Charity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Charity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTaxCapRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTaxCapRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTaxCapRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTaxCapResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTaxCapResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTaxCapResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaxCap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TaxCap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTaxRateLimitsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTaxRateLimitsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTaxRateLimitsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTaxRateLimitsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTaxRateLimitsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTaxRateLimitsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaxRateLimits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TaxRateLimits.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCollectionPeriodsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCollectionPeriodsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCollectionPeriodsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCollectionPeriodsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCollectionPeriodsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCollectionPeriodsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionPeriods", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollectionPeriods = append(m.CollectionPeriods, CollectionPeriod{})
			if err := m.CollectionPeriods[len(m.CollectionPeriods)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
